pub fn macroman_to_char(macroman: u8) -> char {
    match macroman {
        0..=127 => macroman as char,
        128 => 'Ä', // A dieresis
        129 => 'Å', // A ring
        130 => 'Ç', // C cedilla
        131 => 'É', // E acute
        132 => 'Ñ', // N tilde
        133 => 'Ö', // O dieresis
        134 => 'Ü', // U dieresis
        135 => 'á', // a acute
        136 => 'à', // a grave
        137 => 'â', // a circumflex
        138 => 'ä', // a dieresis
        139 => 'ã', // a tilde
        140 => 'å', // a ring
        141 => 'ç', // c cedilla
        142 => 'é', // e acute
        143 => 'è', // e grave
        144 => 'ê', // e circumflex
        145 => 'ë', // e dieresis
        146 => 'í', // i acute
        147 => 'ì', // i grave
        148 => 'î', // i circumflex
        149 => 'ï', // i dieresis
        150 => 'ñ', // n tilde
        151 => 'ó', // o acute
        152 => 'ò', // o grave
        153 => 'ô', // o circumflex
        154 => 'ö', // o dieresis
        155 => 'õ', // o tilde
        156 => 'ú', // u acute
        157 => 'ù', // u grave
        158 => 'û', // u circumflex
        159 => 'ü', // u dieresis
        160 => '†', // dagger
        161 => '°', // degree
        162 => '¢', // cent
        163 => '£', // sterling
        164 => '§', // section
        165 => '•', // bullet
        166 => '¶', // paragraph
        167 => 'ß', // German double s
        168 => '®', // registered
        169 => '©', // copyright
        170 => '™', // trademark
        171 => '´', // acute
        172 => '¨', // diaeresis
        173 => '≠', // not equal to
        174 => 'Æ', // AE
        175 => 'Ø', // O slash
        176 => '∞', // infinity
        177 => '±', // plusminus
        178 => '≤', // less-then
        179 => '≥', // greater-then
        180 => '¥', // yen
        181 => 'µ', // micro
        182 => '∂',
        183 => '∑',
        184 => '∏',
        185 => 'π',
        186 => '∫',
        187 => 'ª', // ordfeminine
        188 => 'º', // ordmasculine
        189 => 'Ω',
        190 => 'æ', // ae
        191 => 'ø', // o slash
        192 => '¿', // question down
        193 => '¡', // exclamation down
        194 => '¬', // not
        195 => '√',
        196 => 'ƒ', // florin
        197 => '≈',
        198 => '∆',
        199 => '«', // left guille
        200 => '»', // right guille
        201 => '…', // ellipsis
        202 => ' ', // non-breaking space
        203 => 'À', // A grave
        204 => 'Ã', // A tilde
        205 => 'Õ', // O tilde
        206 => 'Œ', // OE
        207 => 'œ', // oe
        208 => '–', // endash
        209 => '—', // emdash
        210 => '“', // ldquo
        211 => '”', // rdquo
        212 => '‘', // lsquo
        213 => '’', // rsquo
        214 => '÷', // divide
        215 => '◊',
        216 => 'ÿ', // y dieresis
        217 => 'Ÿ', // Y dieresis
        218 => '⁄', // fraction
        219 => '¤', // currency
        220 => '‹', // left single guille
        221 => '›', // right single guille
        222 => 'ﬁ', // fi
        223 => 'ﬂ', // fl
        224 => '‡', // double dagger
        225 => '·', // middle dot
        226 => '‚', // single quote base
        227 => '„', // double quote base
        228 => '‰', // perthousand
        229 => 'Â', // A circumflex
        230 => 'Ê', // E circumflex
        231 => 'Á', // A acute
        232 => 'Ë', // E dieresis
        233 => 'È', // E grave
        234 => 'Í', // I acute
        235 => 'Î', // I circumflex
        236 => 'Ï', // I dieresis
        237 => 'Ì', // I grave
        238 => 'Ó', // O acute
        239 => 'Ô', // O circumflex
        240 => '',
        241 => 'Ò', // O grave
        242 => 'Ú', // U acute
        243 => 'Û', // U circumflex
        244 => 'Ù', // U grave
        245 => 'ı', // dot-less i
        246 => '^', // circumflex
        247 => '˜', // tilde
        248 => '¯', // macron
        249 => '˘', // breve
        250 => '˙', // dot accent
        251 => '˚', // ring
        252 => '¸', // cedilla
        253 => '˝', // Hungarian umlaut (double acute accent
        254 => '˛', // ogonek
        255 => 'ˇ', // caron
    }
}